name: vaca
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.9.0
  - pip:
    - matplotlib==3.4.3
    - networkx==2.6.3
    - numpy==1.21.2
    - pandas==1.3.4
    - pytorch-lightning==1.4.9
    - scikit-learn==1.0
    - scipy==1.7.1
    - seaborn==0.11.2
    - tensorboard==2.7.0
    - torch==1.9.1
    - torch-cluster==1.5.9
    - torch-geometric==2.0.1
    - torch-scatter==2.0.8
    - torch-sparse==0.6.12
    - torch-spline-conv==1.2.1
    - torchaudio==0.9.1
    - torchmetrics==0.5.1
    - torchvision==0.10.1
    - tqdm==4.62.3
