
optimizer:
  name: adam
  params:
    lr: 0.005
    betas: [0.9, 0.999]
    weight_decay: 1.2e-6 # L2 regularization
scheduler:
  name: exp_lr
  params:
    gamma: 0.99
model:
  name: vaca_piwae
  params:
    architecture: dgnn
    estimator: elbo_iwae #multi elbo_iwae, simple iwaedreg, elbo, iwae
    h_dim_list_dec: [ 16, 16 ]
    h_dim_list_enc: [ 16 ]
    z_dim: 2
    distr_z: normal
    K: 3
    dropout_adj_rate: 0.0
    dropout_adj_pa_rate: 0.2
    norm_categorical: 0 # False, True



